services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: pgdata # The PostgreSQL default database (automatically created at first launch)
    expose:
      - 5432
    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
